[package]
name = "claw"
version = "0.1.0-dev"
authors = ["BD103"]
edition = "2021"

[dependencies]
claw_parse = { path = "crates/claw_parse" }
claw_ir = { path = "crates/claw_ir" }
claw_schema = { path = "crates/claw_schema" }
claw_stdlib = { path = "crates/claw_stdlib" }

[workspace]
members = [
    "crates/claw_driver",
    "crates/claw_parse",
    "crates/claw_ir",
    "crates/claw_schema",
    "crates/claw_stdlib",
    "crates/claw_verify",
]
